# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-23 23:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='forum.Category'),
        ),
    ]
