# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-17 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0009_auto_20160517_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('list_order',), 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-sticky', 'created_date')},
        ),
        migrations.AddField(
            model_name='category',
            name='list_order',
            field=models.PositiveSmallIntegerField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
