# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_auto_20160424_1511'),
        ('profile', '0006_auto_20160415_1337'),
    ]

    operations = [
    ]
