# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-02-22 03:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170221_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(default=products.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.ProductCategory'),
        ),
    ]
